<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Jdice.Worker-9743bd0e-03c7-43e6-87aa-1cf0695d43eb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jdice.Application\Jdice.Application.csproj" />
    <ProjectReference Include="..\Jdice.Infrastructure\Jdice.Infrastructure.csproj" />
  </ItemGroup>
</Project>
